apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployment-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: app-project
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: app/services
    repoURL: https://github.com/J0hn-B/service_mesh.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true