# # Create Kubernetes security policies
# apiVersion: kyverno.io/v1
# kind: ClusterPolicy
# metadata:
#   name: disallow-root-user
# spec:
#   validationFailureAction: audit
#   rules:
#   - name: validate-runAsNonRoot
#     match:
#       resources:
#         kinds:
#         - Pod
#     validate:
#       message: "Running as root user is not allowed. Set runAsNonRoot to true"
#       anyPattern:
#       - spec:
#           securityContext:
#             runAsNonRoot: true
#       - spec:
#           securityContext:
#             runAsUser: ">0"
#       - spec:
#           containers:
#           - securityContext:
#               runAsNonRoot: true
#       - spec:
#           containers:
#           - securityContext:
#               runAsUser: ">0"